services:
  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3001
    restart: unless-stopped
    networks:
      - my_network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=sado
      - PORT=3001
      - USE_MONGO=true
    restart: unless-stopped
    networks:
      - my_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    name: my_network
    driver: bridge

volumes:
  mongodb_data: